name: Update NPM Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - uses: actions/cache@master
      id: cacheNodeModules
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
    - name: yarn install
      if: steps.cacheNodeModules.outputs.cache-hit != 'true'
      run: yarn install
    - run: yarn test
      env:
        CI: true
    - run: yarn build
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
